# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://miopas.github.io/
date_format: "ordinal"
title: Miopas's Blog
subtitle: ""
description: "Miopas's blog"
keywords: Miopas
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Miopas
organization: Lord Camelot
github_username: Miopas
location: Atlanta, US
#email: 

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /home/
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
#subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions

repository: miopas/miopas.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
gitalk:
    owner: miopas
    repo: blog-comments
    clientID: d42449b5fe727e33e83e
    clientSecret: 059bd2547e9a4afbd10df5c0e4b3b17de707f52c
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-1H08D7JCZK
