# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: https://miopas.github.io/blog/
url: https://miopas.github.io
date_format: "ordinal"
title: Miopas
subtitle: ""
title: Miopas
subtitle: ""
description: "Miopas's blog"
keywords: Miopas
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Miopas
organization: Lord Camelot
github_username: Miopas
location: Atlanta, US

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml
#subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: miopas/miopas.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: miopas
    repo: blog-comments
    oauth:
        client_id: d42449b5fe727e33e83e
        client_secret: 059bd2547e9a4afbd10df5c0e4b3b17de707f52c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: miopas
    repo: blog-comments
    clientID: d42449b5fe727e33e83e
    clientSecret: 059bd2547e9a4afbd10df5c0e4b3b17de707f52c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-1H08D7JCZK
